# Production environment values
# Usage: helm install observability ./charts/observability-stack -f values/production.yaml

global:
  storageClass: "gp3"  # AWS EBS gp3 or your preferred storage class

prometheus:
  enabled: true

opentelemetry:
  enabled: true

loki:
  enabled: true  # Enable log aggregation in production

# SLO definitions for your services
slos:
  - name: api-availability
    target: 99.9
    service: api-gateway
    window: 30d
    
  - name: api-latency-p99
    target: 99.0
    service: api-gateway
    threshold: 500ms
    window: 30d

kube-prometheus-stack:
  grafana:
    replicas: 2
    persistence:
      enabled: true
      size: 20Gi
      
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.example.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.example.com
            
  prometheus:
    prometheusSpec:
      replicas: 2
      retention: 30d
      retentionSize: "90GB"
      
      resources:
        requests:
          cpu: 1000m
          memory: 4Gi
        limits:
          cpu: 4000m
          memory: 16Gi
          
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi
                
  alertmanager:
    alertmanagerSpec:
      replicas: 3
      
    config:
      receivers:
        - name: 'default'
          slack_configs:
            - api_url_file: /etc/alertmanager/secrets/slack-webhook/url
              channel: '#alerts'
              
        - name: 'pagerduty-critical'
          pagerduty_configs:
            - service_key_file: /etc/alertmanager/secrets/pagerduty/service-key
              description: '[{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}'
              details:
                severity: '{{ .CommonLabels.severity }}'
                namespace: '{{ .CommonLabels.namespace }}'
                
        - name: 'slack-warnings'
          slack_configs:
            - api_url_file: /etc/alertmanager/secrets/slack-webhook/url
              channel: '#alerts'
              color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
              
        - name: 'slack-info'
          slack_configs:
            - api_url_file: /etc/alertmanager/secrets/slack-webhook/url
              channel: '#alerts-low-priority'

opentelemetry-collector:
  mode: deployment
  replicas: 2
  
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

loki-stack:
  loki:
    persistence:
      enabled: true
      size: 100Gi
