# Kubernetes infrastructure alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  labels:
    app: observability-stack
spec:
  groups:
    - name: kubernetes.pods
      rules:
        - alert: PodCrashLooping
          expr: |
            max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) >= 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
            description: "Pod has been in CrashLoopBackOff for more than 15 minutes."

        - alert: PodNotReady
          expr: |
            min_over_time(kube_pod_status_ready{condition="true"}[10m]) == 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is not ready"
            description: "Pod has been in a non-ready state for more than 15 minutes."

        - alert: ContainerOOMKilled
          expr: |
            (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1)
            and ignoring (reason) kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Container {{ $labels.container }} OOM killed"
            description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} was OOM killed."

    - name: kubernetes.nodes
      rules:
        - alert: NodeNotReady
          expr: |
            kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.node }} is not ready"
            description: "Node has been unready for more than 10 minutes."

        - alert: NodeMemoryPressure
          expr: |
            kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Node {{ $labels.node }} has memory pressure"
            description: "Node is reporting memory pressure."

        - alert: NodeDiskPressure
          expr: |
            kube_node_status_condition{condition="DiskPressure",status="true"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Node {{ $labels.node }} has disk pressure"
            description: "Node is reporting disk pressure."

        - alert: NodeHighCPU
          expr: |
            (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 0.9
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on {{ $labels.instance }}"
            description: "Node CPU usage is above 90% for more than 15 minutes."

        - alert: NodeHighMemory
          expr: |
            (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on {{ $labels.instance }}"
            description: "Node memory usage is above 90% for more than 15 minutes."

    - name: kubernetes.deployments
      rules:
        - alert: DeploymentReplicasMismatch
          expr: |
            (
              kube_deployment_spec_replicas != kube_deployment_status_replicas_available
            ) and (
              changes(kube_deployment_status_replicas_updated[10m]) == 0
            )
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} replicas mismatch"
            description: "Deployment has not matched the expected number of replicas for more than 15 minutes."

        - alert: DeploymentGenerationMismatch
          expr: |
            kube_deployment_status_observed_generation != kube_deployment_metadata_generation
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} generation mismatch"
            description: "Deployment generation does not match, this indicates the deployment has failed but has not been rolled back."

    - name: kubernetes.pvc
      rules:
        - alert: PersistentVolumeClaimPending
          expr: |
            kube_persistentvolumeclaim_status_phase{phase="Pending"} == 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is pending"
            description: "PVC has been pending for more than 15 minutes."

        - alert: PersistentVolumeFilling
          expr: |
            (
              kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes
            ) < 0.1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is filling up"
            description: "PVC has less than 10% space remaining."
